"""add ref_id to order table

Revision ID: 1f14e3cac11e
Revises: ec97917501f7
Create Date: 2021-03-08 18:39:29.163575-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f14e3cac11e'
down_revision = 'ec97917501f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('ref_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_order_ref_id'), 'order', ['ref_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_ref_id'), table_name='order')
    op.drop_column('order', 'ref_id')
    # ### end Alembic commands ###
