"""update Order ref_id to UUID type

Revision ID: 387c21a01c32
Revises: 1f14e3cac11e
Create Date: 2021-03-17 20:46:42.490722-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387c21a01c32'
down_revision = '1f14e3cac11e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_ref_id', table_name='order')
    op.create_unique_constraint(None, 'order', ['ref_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='unique')
    op.create_index('ix_order_ref_id', 'order', ['ref_id'], unique=True)
    # ### end Alembic commands ###
