"""add restaurant_id FK to Order table

Revision ID: 7a0316c80783
Revises: 01436a9497e4
Create Date: 2021-03-28 21:07:37.739609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a0316c80783'
down_revision = '01436a9497e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'restaurant', ['restaurant_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'restaurant_id')
    # ### end Alembic commands ###
