"""update Order ref_id as_uuid

Revision ID: c4f8bae45085
Revises: 387c21a01c32
Create Date: 2021-03-17 20:49:52.437873-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f8bae45085'
down_revision = '387c21a01c32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
