"""add_table_name

Revision ID: ec97917501f7
Revises: c4e532e01d13
Create Date: 2021-03-06 20:19:19.951963-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec97917501f7'
down_revision = 'c4e532e01d13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_table', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_table', 'name')
    # ### end Alembic commands ###
